### ISSUE TITLE
Upstream update tracking

### ISSUE THREAD

**Issue by akerl** [halyard/homebrew-casks#42]
* [ ] Evaluate appcast feeds as the primary means of tracking updates, and check for alternate ways to derive version for casks that don't have appcast feeds.
* [ ] Create gem to read in casks and parse updates via appcast and any other means
* [ ] Add helper script to invoke gem and update cask formulas
* [ ] Support dry-run mode, to detect unhandled updates and alert
* [ ] Set up dry-run to poll periodically and email me

**Comment by akerl** [comment]
This is a ton of overhead, for a few casks, where in most cases I'm lurking their feeds anyways
